using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Microsoft.SqlServer.TransactSql.ScriptDom;

namespace OxfordCC.ContrOCC.SQLUtilities.Business
{
	public class oVisitorAll : oVisitorBase
	{
		public oVisitorAll()
			: base()
		{ }

		public override void ExplicitVisit(AddAlterFullTextIndexAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AddFileSpec fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AddMemberAlterRoleAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AddSearchPropertyListAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AddSignatureStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AdHocDataSource fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AdHocTableReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlgorithmKeyOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterApplicationRoleStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterAssemblyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterAsymmetricKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterAuthorizationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterAvailabilityGroupAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterAvailabilityGroupFailoverAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterAvailabilityGroupFailoverOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterAvailabilityGroupStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterBrokerPriorityStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterCertificateStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterColumnAlterFullTextIndexAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterCreateEndpointStatementBase fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterCreateServiceStatementBase fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterCredentialStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterCryptographicProviderStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterDatabaseAddFileGroupStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterDatabaseAddFileStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterDatabaseAuditSpecificationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterDatabaseCollateStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterDatabaseEncryptionKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterDatabaseModifyFileGroupStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterDatabaseModifyFileStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterDatabaseModifyNameStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterDatabaseRebuildLogStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterDatabaseRemoveFileGroupStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterDatabaseRemoveFileStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterDatabaseSetStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterDatabaseStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterDatabaseTermination fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterEndpointStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterEventSessionStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterFederationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterFullTextCatalogStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterFullTextIndexAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterFullTextIndexStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterFullTextStopListStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterFunctionStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterIndexStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterLoginAddDropCredentialStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterLoginEnableDisableStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterLoginOptionsStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterLoginStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterMasterKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterMessageTypeStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterPartitionFunctionStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterPartitionSchemeStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterProcedureStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterQueueStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterRemoteServiceBindingStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterResourceGovernorStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterResourcePoolStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterRoleAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterRoleStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterRouteStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterSchemaStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterSearchPropertyListStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterSequenceStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterServerAuditSpecificationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterServerAuditStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterServerConfigurationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterServerRoleStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterServiceMasterKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterServiceStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterSymmetricKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterTableAddTableElementStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterTableAlterColumnStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterTableChangeTrackingModificationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterTableConstraintModificationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterTableDropTableElement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterTableDropTableElementStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterTableFileTableNamespaceStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterTableRebuildStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterTableSetStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterTableStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterTableSwitchStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterTableTriggerModificationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterTriggerStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterUserStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterViewStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterWorkloadGroupStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AlterXmlSchemaCollectionStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ApplicationRoleOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ApplicationRoleStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AssemblyEncryptionSource fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AssemblyName fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AssemblyOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AssemblyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AssignmentSetClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AsymmetricKeyCreateLoginSource fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AuditActionGroupReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AuditActionSpecification fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AuditGuidAuditOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AuditOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AuditSpecificationDetail fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AuditSpecificationPart fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AuditSpecificationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AuditTarget fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AuditTargetOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AuthenticationEndpointProtocolOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AuthenticationPayloadOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AutoCleanupChangeTrackingOptionDetail fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AvailabilityGroupOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AvailabilityGroupStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AvailabilityModeReplicaOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AvailabilityReplica fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(AvailabilityReplicaOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BackupCertificateStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BackupDatabaseStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BackupMasterKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BackupOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BackupRestoreFileInfo fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BackupRestoreMasterKeyStatementBase fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BackupServiceMasterKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BackupStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BackupTransactionLogStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BackwardsCompatibleDropIndexClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BeginConversationTimerStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BeginDialogStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BeginEndBlockStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BeginTransactionStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BinaryExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BinaryLiteral fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BinaryQueryExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BooleanBinaryExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BooleanComparisonExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BooleanExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BooleanExpressionSnippet fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BooleanIsNullExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BooleanNotExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BooleanParenthesisExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BooleanTernaryExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BoundingBoxParameter fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BoundingBoxSpatialIndexOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BreakStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BrokerPriorityParameter fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BrokerPriorityStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BrowseForClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BuiltInFunctionTableReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BulkInsertBase fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BulkInsertOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BulkInsertStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(BulkOpenRowset fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CallTarget fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CaseExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CastCall fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CellsPerObjectSpatialIndexOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CertificateCreateLoginSource fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CertificateOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CertificateStatementBase fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ChangeRetentionChangeTrackingOptionDetail fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ChangeTableChangesTableReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ChangeTableVersionTableReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ChangeTrackingDatabaseOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ChangeTrackingFullTextIndexOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ChangeTrackingOptionDetail fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CharacterSetPayloadOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CheckConstraintDefinition fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CheckpointStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ChildObjectName fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CloseCursorStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CloseMasterKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CloseSymmetricKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CoalesceExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ColumnDefinition fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ColumnDefinitionBase fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ColumnReferenceExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ColumnStorageOptions fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ColumnWithSortOrder fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CommandSecurityElement80 fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CommitTransactionStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CommonTableExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CompositeGroupingSpecification fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CompressionEndpointProtocolOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CompressionPartitionRange fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ComputeClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ComputeFunction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ConstraintDefinition fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ContainmentDatabaseOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ContinueStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ContractMessage fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ConvertCall fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateAggregateStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateApplicationRoleStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateAssemblyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateAsymmetricKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateAvailabilityGroupStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateBrokerPriorityStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateCertificateStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateColumnStoreIndexStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateContractStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateCredentialStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateCryptographicProviderStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateDatabaseAuditSpecificationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateDatabaseEncryptionKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateDatabaseStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateDefaultStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateEndpointStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateEventNotificationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateEventSessionStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateFederationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateFullTextCatalogStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateFullTextIndexStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateFullTextStopListStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateFunctionStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateIndexStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateLoginSource fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateLoginStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateMasterKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateMessageTypeStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreatePartitionFunctionStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreatePartitionSchemeStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateProcedureStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateQueueStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateRemoteServiceBindingStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateResourcePoolStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateRoleStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateRouteStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateRuleStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateSchemaStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateSearchPropertyListStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateSequenceStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateServerAuditSpecificationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateServerAuditStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateServerRoleStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateServiceStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateSpatialIndexStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateStatisticsStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateSymmetricKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateSynonymStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateTableStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateTriggerStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateTypeStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateTypeTableStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateTypeUddtStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateTypeUdtStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateUserStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateViewStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateWorkloadGroupStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateXmlIndexStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreateXmlSchemaCollectionStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CreationDispositionKeyOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CredentialStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CryptoMechanism fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CubeGroupingSpecification fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CursorDefaultDatabaseOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CursorDefinition fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CursorId fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CursorOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(CursorStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DatabaseAuditAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DatabaseEncryptionKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DatabaseOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DataCompressionOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DataModificationSpecification fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DataModificationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DataModificationTableReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DataTypeReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DataTypeSequenceOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DbccNamedLiteral fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DbccOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DbccStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DeallocateCursorStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DeclareCursorStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DeclareTableVariableBody fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DeclareTableVariableStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DeclareVariableElement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DeclareVariableStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DefaultConstraintDefinition fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DefaultLiteral fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DeleteMergeAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DeleteSpecification fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DeleteStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DenyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DenyStatement80 fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DeviceInfo fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DialogOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DiskStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DiskStatementOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropAggregateStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropAlterFullTextIndexAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropApplicationRoleStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropAssemblyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropAsymmetricKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropAvailabilityGroupStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropBrokerPriorityStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropCertificateStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropChildObjectsStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropClusteredConstraintMoveOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropClusteredConstraintOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropClusteredConstraintStateOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropClusteredConstraintValueOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropContractStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropCredentialStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropCryptographicProviderStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropDatabaseAuditSpecificationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropDatabaseEncryptionKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropDatabaseStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropDefaultStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropEndpointStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropEventNotificationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropEventSessionStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropFederationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropFullTextCatalogStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropFullTextIndexStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropFullTextStopListStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropFunctionStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropIndexClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropIndexClauseBase fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropIndexStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropLoginStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropMasterKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropMemberAlterRoleAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropMessageTypeStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropObjectsStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropPartitionFunctionStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropPartitionSchemeStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropProcedureStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropQueueStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropRemoteServiceBindingStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropResourcePoolStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropRoleStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropRouteStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropRuleStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropSchemaStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropSearchPropertyListAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropSearchPropertyListStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropSequenceStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropServerAuditSpecificationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropServerAuditStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropServerRoleStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropServiceStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropSignatureStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropStatisticsStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropSymmetricKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropSynonymStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropTableStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropTriggerStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropTypeStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropUnownedObjectStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropUserStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropViewStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropWorkloadGroupStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(DropXmlSchemaCollectionStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(EnabledDisabledPayloadOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(EnableDisableTriggerStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(EncryptionPayloadOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(EncryptionSource fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(EndConversationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(EndpointAffinity fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(EndpointProtocolOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(EventDeclaration fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(EventDeclarationCompareFunctionParameter fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(EventDeclarationSetParameter fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(EventGroupContainer fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(EventNotificationObjectScope fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(EventRetentionSessionOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(EventSessionObjectName fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(EventSessionStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(EventTypeContainer fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(EventTypeGroupContainer fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ExecutableEntity fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ExecutableProcedureReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ExecutableStringList fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ExecuteAsClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ExecuteAsFunctionOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ExecuteAsProcedureOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ExecuteAsStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ExecuteAsTriggerOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ExecuteContext fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ExecuteInsertSource fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ExecuteOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ExecuteParameter fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ExecuteSpecification fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ExecuteStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ExistsPredicate fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ExpressionCallTarget fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ExpressionGroupingSpecification fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ExpressionWithSortOrder fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ExtractFromExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FailoverModeReplicaOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FederationScheme fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FetchCursorStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FetchType fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FileDeclaration fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FileDeclarationOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FileEncryptionSource fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FileGroupDefinition fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FileGroupOrPartitionScheme fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FileGrowthFileDeclarationOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FileNameFileDeclarationOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FileStreamDatabaseOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FileStreamOnDropIndexOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FileStreamOnTableOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FileStreamRestoreOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FileTableCollateFileNameTableOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FileTableConstraintNameTableOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FileTableDirectoryTableOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ForceSeekTableHint fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ForClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ForeignKeyConstraintDefinition fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FromClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FullTextCatalogAndFileGroup fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FullTextCatalogOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FullTextCatalogStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FullTextIndexColumn fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FullTextIndexOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FullTextPredicate fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FullTextStopListAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FullTextTableReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FunctionCall fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FunctionCallSetClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FunctionOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FunctionReturnType fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(FunctionStatementBody fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(GeneralSetCommand fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(GetConversationGroupStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(GlobalVariableExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(GoToStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(GrandTotalGroupingSpecification fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(GrantStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(GrantStatement80 fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(GridParameter fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(GridsSpatialIndexOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(GroupByClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(GroupingSetsGroupingSpecification fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(GroupingSpecification fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(HadrAvailabilityGroupDatabaseOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(HadrDatabaseOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(HavingClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(Identifier fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(IdentifierDatabaseOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(IdentifierLiteral fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(IdentifierOrValueExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(IdentifierPrincipalOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(IdentifierSnippet fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(IdentityFunctionCall fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(IdentityOptions fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(IdentityValueKeyOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(IfStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(IIfCall fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(IndexExpressionOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(IndexOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(IndexStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(IndexStateOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(IndexTableHint fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(InlineDerivedTable fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(InlineResultSetDefinition fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(InPredicate fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(InsertBulkColumnDefinition fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(InsertBulkStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(InsertMergeAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(InsertSource fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(InsertSpecification fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(InsertStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(IntegerLiteral fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(InternalOpenRowset fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(IPv4 fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(JoinParenthesisTableReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(JoinTableReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(KeyOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(KeySourceKeyOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(KillQueryNotificationSubscriptionStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(KillStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(KillStatsJobStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(LabelStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(LeftFunctionCall fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(LikePredicate fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(LineNoStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ListenerIPEndpointProtocolOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(Literal fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(LiteralAuditTargetOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(LiteralAvailabilityGroupOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(LiteralBulkInsertOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(LiteralDatabaseOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(LiteralEndpointProtocolOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(LiteralOptimizerHint fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(LiteralPayloadOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(LiteralPrincipalOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(LiteralRange fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(LiteralReplicaOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(LiteralSessionOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(LiteralStatisticsOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(LiteralTableHint fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(LockEscalationTableOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(LoginTypePayloadOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(MasterKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(MaxDispatchLatencySessionOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(MaxLiteral fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(MaxRolloverFilesAuditTargetOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(MaxSizeAuditTargetOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(MaxSizeDatabaseOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(MaxSizeFileDeclarationOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(MemoryPartitionSessionOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(MergeAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(MergeActionClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(MergeSpecification fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(MergeStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(MessageTypeStatementBase fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(MethodSpecifier fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(MirrorToClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(MoneyLiteral fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(MoveConversationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(MoveRestoreOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(MoveToDropIndexOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(MultiPartIdentifier fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(MultiPartIdentifierCallTarget fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(NamedTableReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(NameFileDeclarationOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(NextValueForExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(NullableConstraintDefinition fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(NullIfExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(NullLiteral fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(NumericLiteral fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OdbcConvertSpecification fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OdbcFunctionCall fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OdbcLiteral fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OdbcQualifiedJoinTableReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OffsetClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OnFailureAuditOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OnOffAssemblyOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OnOffAuditTargetOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OnOffDatabaseOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OnOffDialogOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OnOffFullTextCatalogOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OnOffPrincipalOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OnOffRemoteServiceBindingOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OnOffSessionOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OpenCursorStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OpenMasterKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OpenQueryTableReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OpenRowsetTableReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OpenSymmetricKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OpenXmlTableReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OptimizeForOptimizerHint fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OptimizerHint fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OrderBulkInsertOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OrderByClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OutputClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OutputIntoClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(OverClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(PageVerifyDatabaseOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ParameterizationDatabaseOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ParameterizedDataTypeReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ParameterlessCall fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ParenthesisExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ParseCall fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(PartitionFunctionCall fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(PartitionParameterType fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(PartitionSpecifier fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(PartnerDatabaseOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(PasswordAlterPrincipalOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(PasswordCreateLoginSource fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(PayloadOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(Permission fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(PermissionSetAssemblyOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(PivotedTableReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(PortsEndpointProtocolOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(PredicateSetStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(PrimaryExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(PrimaryRoleReplicaOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(PrincipalOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(PrintStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(Privilege80 fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(PrivilegeSecurityElement80 fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ProcedureOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ProcedureParameter fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ProcedureReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ProcedureReferenceName fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ProcedureStatementBody fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ProcedureStatementBodyBase fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ProcessAffinityRange fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ProviderEncryptionSource fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ProviderKeyNameKeyOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(QualifiedJoin fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(QueryDerivedTable fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(QueryExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(QueryParenthesisExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(QuerySpecification fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(QueueDelayAuditOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(QueueExecuteAsOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(QueueOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(QueueProcedureOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(QueueStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(QueueStateOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(QueueValueOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RaiseErrorLegacyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RaiseErrorStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ReadOnlyForClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ReadTextStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RealLiteral fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ReceiveStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ReconfigureStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RecoveryDatabaseOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RemoteServiceBindingOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RemoteServiceBindingStatementBase fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RenameAlterRoleAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ResourcePoolAffinitySpecification fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ResourcePoolParameter fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ResourcePoolStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RestoreMasterKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RestoreOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RestoreServiceMasterKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RestoreStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ResultColumnDefinition fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ResultSetDefinition fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ResultSetsExecuteOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ReturnStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RevertStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RevokeStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RevokeStatement80 fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RightFunctionCall fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RolePayloadOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RoleStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RollbackTransactionStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RollupGroupingSpecification fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RouteOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RouteStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(RowValue fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SaveTransactionStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ScalarExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ScalarExpressionDialogOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ScalarExpressionRestoreOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ScalarExpressionSequenceOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ScalarExpressionSnippet fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ScalarFunctionReturnType fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ScalarSubquery fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SchemaDeclarationItem fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SchemaObjectFunctionTableReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SchemaObjectName fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SchemaObjectNameOrValueExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SchemaObjectNameSnippet fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SchemaObjectResultSetDefinition fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SchemaPayloadOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SearchedCaseExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SearchedWhenClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SearchPropertyListAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SearchPropertyListFullTextIndexOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SecondaryRoleReplicaOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SecurityElement80 fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SecurityPrincipal fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SecurityStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SecurityStatementBody80 fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SecurityTargetObject fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SecurityTargetObjectName fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SecurityUserClause80 fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SelectElement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SelectFunctionReturnType fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SelectInsertSource fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SelectScalarExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SelectSetVariable fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SelectStarExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SelectStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SelectStatementSnippet fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SemanticTableReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SendStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SequenceOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SequenceStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ServerAuditStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ServiceContract fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SessionOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SessionTimeoutPayloadOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SetClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SetCommand fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SetCommandStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SetErrorLevelStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SetFipsFlaggerCommand fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SetIdentityInsertStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SetOffsetsStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SetOnOffStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SetRowCountStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SetSearchPropertyListAlterFullTextIndexAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SetStatisticsStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SetStopListAlterFullTextIndexAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SetTextSizeStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SetTransactionIsolationLevelStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SetUserStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SetVariableStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ShutdownStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SignatureStatementBase fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SimpleAlterFullTextIndexAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SimpleCaseExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SimpleWhenClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SizeFileDeclarationOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SoapMethod fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SourceDeclaration fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SpatialIndexOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SpatialIndexRegularOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SqlCommandIdentifier fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SqlDataTypeReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(StateAuditOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(StatementList fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(StatementListSnippet fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(StatementWithCtesAndXmlNamespaces fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(StatisticsOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(StopListFullTextIndexOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(StopRestoreOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(StringLiteral fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SubqueryComparisonPredicate fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(SymmetricKeyStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TableDataCompressionOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TableDefinition fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TableHint fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TableHintsOptimizerHint fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TableOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TableReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TableReferenceWithAlias fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TableReferenceWithAliasAndColumns fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TableSampleClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TableValuedFunctionReturnType fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TargetDeclaration fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TargetRecoveryTimeDatabaseOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TextModificationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ThrowStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TopRowFilter fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TransactionStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TriggerAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TriggerObject fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TriggerOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TriggerStatementBody fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TruncateTableStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TryCastCall fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TryCatchStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TryConvertCall fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TryParseCall fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TSEqualCall fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TSqlBatch fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TSqlFragmentSnippet fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TSqlScript fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TSqlStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(TSqlStatementSnippet fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(UnaryExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(UniqueConstraintDefinition fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(UnpivotedTableReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(UnqualifiedJoin fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(UpdateCall fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(UpdateDeleteSpecificationBase fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(UpdateForClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(UpdateMergeAction fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(UpdateSpecification fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(UpdateStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(UpdateStatisticsStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(UpdateTextStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(UseFederationStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(UserDataTypeReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(UserDefinedTypeCallTarget fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(UserDefinedTypePropertyAccess fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(UserLoginOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(UserRemoteServiceBindingOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(UserStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(UseStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ValueExpression fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ValuesInsertSource fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(VariableMethodCallTableReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(VariableReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(VariableTableReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(VariableValuePair fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ViewOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(ViewStatementBody fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(WaitForStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(WaitForSupportedStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(WhenClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(WhereClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(WhileStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(WindowDelimiter fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(WindowFrameClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(WindowsCreateLoginSource fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(WithCtesAndXmlNamespaces fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(WithinGroupClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(WitnessDatabaseOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(WorkloadGroupImportanceParameter fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(WorkloadGroupParameter fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(WorkloadGroupResourceParameter fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(WorkloadGroupStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(WriteTextStatement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(WsdlPayloadOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(XmlDataTypeReference fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(XmlForClause fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(XmlForClauseOption fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(XmlNamespaces fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(XmlNamespacesAliasElement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(XmlNamespacesDefaultElement fragment) { _fragments.Add(fragment); }
		public override void ExplicitVisit(XmlNamespacesElement fragment) { _fragments.Add(fragment); }
	}
}
